### PR TITLE
TLS InsecureSkipVerify option

### PR DESCRIPTION
**Pull request by vladimirdulov**
@paskal @umputun please review implementation of TLS InsecureSkipVerify option.

### CODE REVIEW

**Review by paskal — APPROVED** [review]

**Comment by vladimirdulov** [comment]
@umputun could you merge it so we can update the mod in remark42 accordingly, thanks.

**Comment by umputun** [comment]
@vladimirdulov i have tagged email package, pls updated deps to have the stable version in instead of the master

**Comment by vladimirdulov** [comment]
OK, it's been updated in both mods: `notify` and `auth`.
A new PR created for `auth` mod update.
https://github.com/go-pkgz/auth/pull/191

**Comment by vladimirdulov** [comment]
@umputun could you review and merge it?

**Pull request merged**
